In [27]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report,recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
data = pd.read_csv("novagen_dataset.csv")

In [20]:
df = pd.read_csv("novagen_dataset.csv")
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

# Creating a BaselineModel

In [22]:


#split features and target variable
X = df.drop("Target", axis=1)
y = df["Target"]
X.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [23]:
#split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42, stratify=y 
) # stratify to maintain class distribution in train and test sets

In [24]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
#Logistic Regression with Reguralization
log_reg = LogisticRegression(
    penalty = "l2",
    solver = "liblinear", # solver here is important for small datasets and binary classification (what solver does that is it optimizes the loss function) liblinear is good for small datasets and binary classification
    max_iter = 1000,
)

log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

# in model Evaluation, we will use recall instead of accuracy because missing high risk patients(false negatives) is more dangerous than false positives
print("Logistic Regression Classification Report:")
print(classification_report(y_test, y_pred_lr))

print("Logistic Regression Recall Score:", recall_score(y_test, y_pred_lr))
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.80      0.80       914
           1       0.82      0.83      0.82       996

    accuracy                           0.81      1910
   macro avg       0.81      0.81      0.81      1910
weighted avg       0.81      0.81      0.81      1910

Logistic Regression Recall Score: 0.8283132530120482
Logistic Regression Accuracy: 0.8141361256544503

# Model 2 - KNN

In [29]:
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric='euclidean' # metric is important because it defines how distance is calculated between points, euclidean is the most common and works well for most cases
    )
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)

print("KNN accuracy : ", accuracy_score(y_test, y_pred_knn ))
print("KNN Recall Score : ", recall_score(y_test, y_pred_knn))
print("KNN Classification Report : \n", classification_report(y_test, y_pred_knn))

KNN accuracy :  0.8832460732984293
KNN Recall Score :  0.8835341365461847
KNN Classification Report :
               precision    recall  f1-score   support

           0       0.87      0.88      0.88       914
           1       0.89      0.88      0.89       996

    accuracy                           0.88      1910
   macro avg       0.88      0.88      0.88      1910
weighted avg       0.88      0.88      0.88      1910

# Random Forest (Ensemble Learning)

In [30]:
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42
)
rf.fit(X_train_scaled, y_train)

y_pred_rf = rf.predict(X_test_scaled)
print("RandomForest accuracy_score :", accuracy_score(y_test, y_pred_rf))
print("RandomForest Recall Score :", recall_score(y_test, y_pred_rf))
print("RandomForest Classification Report : \n", classification_report(y_test, y_pred_rf))

RandomForest accuracy_score : 0.9366492146596859
RandomForest Recall Score : 0.9548192771084337
RandomForest Classification Report :
               precision    recall  f1-score   support

           0       0.95      0.92      0.93       914
           1       0.93      0.95      0.94       996

    accuracy                           0.94      1910
   macro avg       0.94      0.94      0.94      1910
weighted avg       0.94      0.94      0.94      1910

# Gradient boosting (ensemble learning)

##### gradient boosing uses decision trees as base learners and builds them sequentially, where each new tree tries to correct the errors made by the previous trees. It is a powerful ensemble technique that can handle complex datasets and capture non-linear relationships.

In [31]:
#
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
gb.fit(X_train_scaled, y_train)
y_pred_gb = gb.predict(X_test_scaled)
print("GradientBoosting accuracy_score :", accuracy_score(y_test, y_pred_gb))
print("GradientBoosting Recall Score :", recall_score(y_test, y_pred_gb))
print("GradientBoosting Classification Report : \n", classification_report(y_test, y_pred_gb))

GradientBoosting accuracy_score : 0.9198952879581151
GradientBoosting Recall Score : 0.9447791164658634
GradientBoosting Classification Report :
               precision    recall  f1-score   support

           0       0.94      0.89      0.91       914
           1       0.91      0.94      0.92       996

    accuracy                           0.92      1910
   macro avg       0.92      0.92      0.92      1910
weighted avg       0.92      0.92      0.92      1910

# Voting Classifier

In [32]:
voting_clf = VotingClassifier(
    estimators=[
        ('lr', log_reg),
        ('knn', knn),
        ('rf', rf),
        ('gb', gb)
    ],
    voting='soft' # soft voting uses predicted probabilities to make the final prediction, which is better for imbalanced datasets
)
voting_clf.fit(X_train_scaled, y_train)
y_pred_voting = voting_clf.predict(X_test_scaled)

print("Voting Classifier accuracy_score :", accuracy_score(y_test, y_pred_voting))
print("Voting Classifier Recall Score :", recall_score(y_test, y_pred_voting))
print("Voting Classifier Classification Report : \n", classification_report(y_test, y_pred_voting))

Voting Classifier accuracy_score : 0.9246073298429319
Voting Classifier Recall Score : 0.9457831325301205
Voting Classifier Classification Report :
               precision    recall  f1-score   support

           0       0.94      0.90      0.92       914
           1       0.91      0.95      0.93       996

    accuracy                           0.92      1910
   macro avg       0.93      0.92      0.92      1910
weighted avg       0.93      0.92      0.92      1910

# Results

## Model Performance Summary

| Model                | Recall Score | Accuracy Score |
|----------------------|-------------:|---------------:|
| Logistic Regression  | *(from output)* | *(from output)* |
| K-Nearest Neighbors  | *(from output)* | *(from output)* |
| Random Forest        | *(from output)* | *(from output)* |
| Gradient Boosting    | *(from output)* | *(from output)* |
| Voting Classifier    | *(from output)* | *(from output)* |

> Recall is prioritized for this problem because reducing false negatives (missing high-risk patients) is more important than maximizing overall accuracy.